### ISSUE TITLE
New chapters this month

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/newsletter#11]
Hey, do we have any way to calculate some fun facts each month such as how many new chapters, who they were, how many events, what continents?

**Comment by RichardLitt** [comment]
I don't think so. We could manually do this, but there might be a way to automate.

**Comment by iancrowther** [comment]
I just need to study the api docs a little.

**Comment by martinheidegger** [comment]
This could be a "feature" of [open-github-teams](https://github.com/martinheidegger/open-github-teams)

**Comment by iancrowther** [comment]
sounds good to me, should I move https://github.com/nodeschool/newsletter/issues/12 over to OGT then?

**Comment by martinheidegger** [comment]
https://github.com/martinheidegger/open-github-teams/issues/2

**Comment by iancrowther** [comment]
How best to manage this issue as it has dependencies on work that *may get done in the future?

I'm sure it will all get done, but I'm also conscious not to introduce an issue that just hangs for a few months.

Should we close for now?

**Comment by iancrowther** [comment]
in fact scratch that, the question has been answered.  

We dont have any tools currently, we may do in the future
