### ISSUE TITLE
Newsletter #2 planning thread

### ISSUE THREAD

**Issue by maxogden** [nodeschool/newsletter#4]
Hey all,

**Anyone wanna take a stab at writing a segment for newsletter #2**? We have over 700 subscribers now and have sent one newsletter out so far.

Here's #1 for reference: https://github.com/nodeschool/newsletter/blob/master/01-nov-14.md

A segment should be a couple paragraphs and a couple photos, in markdown. Tell a story. **Feel free to write it below in the comments and I'll incorporate it into the next newsletter.**

Ideas for segments:

- Reviews of events in the style of [this thread](https://github.com/nodeschool/discussions/issues/93)
- Workshop spotlight, to get readers excited about a workshop that they might not try on their own
- Pretty much anything else you think people might wanna hear about!

I'm hoping to send it out in the next couple of weeks, so get your segments in below! If you write something up and it doesnt get used for this next one it will get used in the future.

**Comment by maxogden** [comment]
Just wanted to update and say that we have 1200+ subscribers now. Anyone wanna take a stab at drafting the next newsletter?

**Comment by martinheidegger** [comment]
I started to add content to https://github.com/nodeschool/newsletter/tree/master/things_to_write_about This way we don't need to write the whole newsletter but accumulate part of things to go there.

**Comment by maxogden** [comment]
sent!
